// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRfyNCKEzOTF-YXbJpgx_jJ3wUOaQhAKc',
    appId: '1:975093260706:web:7e5827ce66ea9337e852fb',
    messagingSenderId: '975093260706',
    projectId: 'flutter-chatapp-8164d',
    authDomain: 'flutter-chatapp-8164d.firebaseapp.com',
    storageBucket: 'flutter-chatapp-8164d.firebasestorage.app',
    measurementId: 'G-1ME77Q1EW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt5F30EAubMCO1jMhX6VYBDdv6WGgSOq4',
    appId: '1:975093260706:android:35fc44a5086a62e1e852fb',
    messagingSenderId: '975093260706',
    projectId: 'flutter-chatapp-8164d',
    storageBucket: 'flutter-chatapp-8164d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxoMboll35FSE1TNj2Wp8MXKvD8lcXeus',
    appId: '1:975093260706:ios:52b0fa40132d2ddbe852fb',
    messagingSenderId: '975093260706',
    projectId: 'flutter-chatapp-8164d',
    storageBucket: 'flutter-chatapp-8164d.firebasestorage.app',
    iosBundleId: 'com.example.demo7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxoMboll35FSE1TNj2Wp8MXKvD8lcXeus',
    appId: '1:975093260706:ios:52b0fa40132d2ddbe852fb',
    messagingSenderId: '975093260706',
    projectId: 'flutter-chatapp-8164d',
    storageBucket: 'flutter-chatapp-8164d.firebasestorage.app',
    iosBundleId: 'com.example.demo7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRfyNCKEzOTF-YXbJpgx_jJ3wUOaQhAKc',
    appId: '1:975093260706:web:b1ffc7521d5bdcc7e852fb',
    messagingSenderId: '975093260706',
    projectId: 'flutter-chatapp-8164d',
    authDomain: 'flutter-chatapp-8164d.firebaseapp.com',
    storageBucket: 'flutter-chatapp-8164d.firebasestorage.app',
    measurementId: 'G-YFH32M8WJJ',
  );
}